GET {{MedievalEra.Server_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{MedievalEra.Server_HostAddress}}/menu/items
Accept: application/json

###
GET {{MedievalEra.Server_HostAddress}}/dice
Accept: application/json

###
GET {{MedievalEra.Server_HostAddress}}/dice/GetStarterKit
Accept: application/json