@MedievalEra.Server_HostAddress = http://localhost:5071

###
GET {{MedievalEra.Server_HostAddress}}/menu/items
Accept: application/json

###
GET {{MedievalEra.Server_HostAddress}}/dice
Accept: application/json

###
GET {{MedievalEra.Server_HostAddress}}/dice/starterKit
Accept: application/json